language: python

python:
  - 3.8

install:
  - pip install -r mysite/requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test
