language: python

python:
  - 3.8

install:
  - pip install -r mysite/requirements.txt

before_script:
  - python mysite/manage.py migrate
  - python mmysite/anage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite/mysite,manage.py test polls
